services:
  - type: web
    name: algoforall-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATA_STORE_PATH
        value: /opt/render/project/src/data_store
